### ISSUE TITLE
old versions of glibc don't have be64toh

### ISSUE THREAD

**Issue by dgleich** [bwhite/hadoopy#3]
Hey Brian, 

This package looks awesome.  Thanks for making it available.  Unfortunately, I'm stuck on a cluster with an ancient version of glibc.  This glibc doesn't have the handy big-endian routines you use in the typed bytes files.  

Python 2.6.5 (r265:79063, Jun  4 2010, 21:42:56) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-48)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import hadoopy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/dfgleic/envs26/hadoopy/lib/python2.6/site-packages/hadoopy/**init**.py", line 25, in <module>
> > >     from _typedbytes import TypedBytesFile
> > > ImportError: /home/dfgleic/envs26/hadoopy/lib/python2.6/site-packages/_typedbytes.so: undefined symbol: be64toh

I wrote the following quick code to convert them, which I haven't extensively tested yet. (i.e. don't trust it without further testing).  Based on the C code generated, this looks much slower.  If you have any ideas for "optionally" including these functions as c code themselves, I'd be happy to test it out.

cdef inline int be32toh(int val):
    cdef unsigned char\* c = <unsigned char*>&val
    return int( (int(c[0] & 255) << 24) + (int(c[1] & 255) << 16) + 
         (int(c[2] & 255) <<  8) + (int(c[3] & 255)) )

cdef inline int htobe32(int i):
    cdef int rval
    cdef unsigned char _c = <unsigned char_>&rval
    c[0] = (i >> 24)&255
    c[1] = (i >> 16)&255
    c[2] = (i >> 8)&255
    c[3] = (i)&255
    return rval

cdef inline long be64toh(long val):
    cdef unsigned char\* c = <unsigned char*>&val
    return long( (long((c[0] & 255)) << 56) + 
         (long(c[1] & 255) << 48) +
         (long(c[2] & 255) << 40) + 
         (long(c[3] & 255) << 32) +
         (long(c[4] & 255) << 24) +
         (long(c[5] & 255) << 16) +
         (long(c[6] & 255) <<  8) +
         (long(c[7] & 255)      ) )

cdef inline long htobe64(long l):
    cdef long rval
    cdef unsigned char\* c = <unsigned char*>&rval
    c[0] = (l >> 56) & 255
    c[1] = (l >> 48) & 255
    c[2] = (l >> 40) & 255
    c[3] = (l >> 32) & 255
    c[4] = (l >> 24) & 255
    c[5] = (l >> 16) & 255
    c[6] = (l >>  8) & 255
    c[7] = (l      ) & 255
    return rval

**Comment by bwhite** [comment]
I have a branch called endian. Try this out an let me know if it fixes the problem.  

There are very fast byteswap assembly commands that are used to implement the htobe64 and others, so I tried to use the library code as much as possible.  Since htonl is more commonly available, I use that to swap the 32bit values.  For 64bit values I use htonl for each part and then combine them.

The result is nearly as fast as the endian.h version but should be available to everyone.  The only thing better than this would be to implement those in assembly like the endian.h ones are; however, it probably isn't worth it.

**Comment by dgleich** [comment]
Thanks!  I should get a chance to check it out really soon and will let you know.

**Comment by dgleich** [comment]
Turns out that quick ldd check didn't work on my platform either :-).  My glibc only has a major/minor number!  

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.

I committed a change to use the platform package, which will detect the version of glibc that python itself was compiled with (or an arbitrary executable).  

https://github.com/dgleich/hadoopy (endian branch)

This isn't ideal as the system may have a more recent version of glibc.  However, it would seem like the most prudent thing would be to directly check for the functions themselves with some sort of autoconf like check.

The other alternative is to modify the ldd --version check to look for one or two integer pairs.  Ick.  You'd think there'd be a very standard way of getting this info!

**Comment by bwhite** [comment]
There isn't a standard way to get this info in python unfortunately.  I used the platform module originally for this task but it isn't very useful because I have a very up to data glibc on my machine, but using platform it would lead us to believe I couldn't use the endian.h functions.  I know it's a hack to check using ldd but it at least gives you the correct information (though parsing it may be a challenge).  Also, build tools are already required so it is fair to assume ldd is available.

For now I'll just update the parser to work for your case too, but I'm certainly open to a "correct" solution that is more reliable and as accurate.  It is easy enough to drop in if we come up with something.

**Comment by bwhite** [comment]
I added this patch into master

**Comment by dgleich** [comment]
It looks like byteswap.h has assembly versions back to glibc 2.  I'll work on using these functions in your byte_conversion routine soon, but I'll check here in case you start on it first.

**Comment by bwhite** [comment]
I'll let you do that if you want, that'll be helpful.  I'll benchmark all of them and we can see what the improvement is (it should only effect the little endian 64bit swap performance).

**Comment by dgleich** [comment]
Okay.  It could be a little bit before I get around to it (a few days).  I'm running a whole bunch of comparisons against different approaches to the same problem.  For this task, hadoopy ends up being considerably (about 40%) faster than dumbo because it involves reading many floating point numbers.

**Comment by bwhite** [comment]
Sure take your time on it, what we have now is a reasonable fallback.  That's great to hear that it is faster.  There are still optimization opportunities available in hadoopy, I'll take a stab at some now.  By looking at the generated code in _typedbytes.c and _main.c you can find several places where a slightly different way of coding the file would make it much faster.

**Comment by bwhite** [comment]
The current master has some more optimizations in typedbytes and also the streaming code.

**Comment by bwhite** [comment]
As this issue is now fixed I'm closing this
